### ISSUE TITLE
error in lib\rest.js line 258

### ISSUE THREAD

**Issue by jfi800** [pgonzaleznetwork/sfdc-goodbye-api#2]
Hi,

I am getting the following error when running the package. Any idea what's causing this in the lib\rest.js?

Thanks.

C:\temp\Salesforce_Code\sfdc-goodbye-api\node_modules\sfdc-happy-api\lib\rest.js:258
    if(Array.isArray(jsonResponse) && jsonResponse[0]?.message == `Cannot retrieve documents in a user's private folder; move the doc
ument to a named folder`){
                                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1071:16)
    at Module._compile (internal/modules/cjs/loader.js:1121:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\temp\Salesforce_Code\sfdc-goodbye-api\node_modules\sfdc-happy-api\src\index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sfdc-goodbye-api@1.0.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sfdc-goodbye-api@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by pgonzaleznetwork** [comment]
That's very strange. Have you tried updating your version of NPM and javascript?

**Comment by jfi800** [comment]
Thanks Pablo.

That resolved the error. Completes without errors but the generated output files only contain the column header.

***@***.***

Here's output of the query retrieving the event log files.
***@***.***

Thanks,

Jean-François Ille
The Coca-Cola Company
404-676-5118



Classified - Confidential

**Comment by pgonzaleznetwork** [comment]
Hi Jean,

Sorry, no clue. I'm no longer maintaining this repository.
